export * from "./Android.icon";
export * from "./Apple.icon";
export * from "./Arrow.icon";
export * from "./ArrowRounded.icon";
export * from "./Chrome.icon";
export * from "./Close.cion";
export * from "./Devices.icon";
export * from "./Linux.icon";
export * from "./Windows.icon";
