export * from "./Accordions/Accordions";
export * from "./Download/Download";
export * from "./Instructions/Instructions";
export * from "./MainScreen/MainScreen";
export * from "./Rates/Rates";
export * from "./Steps/Steps";
export * from "./TermsOfUse/TermsOfUse";
export * from "./TextCards/TextCards";
export * from "./TextWithButton/TextWithButton";
